/*
 * Copyright 2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.graphite;

import java.util.Collections;
import java.util.Map;
import org.jetbrains.annotations.NotNull;

/**
 * Represents a GraphQL operation (query or mutation) that can be executed.
 *
 * <p>This interface captures all the information needed to execute a GraphQL operation against a
 * server:
 *
 * <ul>
 *   <li>The operation name for identification and debugging
 *   <li>The GraphQL query/mutation string
 *   <li>Any variables to be sent with the operation
 *   <li>The expected response type for deserialization
 * </ul>
 *
 * <p>Implementations are typically generated by the Graphite code generator based on the GraphQL
 * schema, providing type-safe query building.
 *
 * <p>Example usage:
 *
 * <pre>{@code
 * // Generated operation class
 * public class GetUserQuery implements GraphQLOperation<UserDTO> {
 *     private final String userId;
 *
 *     public GetUserQuery(String userId) {
 *         this.userId = userId;
 *     }
 *
 *     @Override
 *     public String operationName() {
 *         return "GetUser";
 *     }
 *
 *     @Override
 *     public String toGraphQL() {
 *         return "query GetUser($id: ID!) { user(id: $id) { id name email } }";
 *     }
 *
 *     @Override
 *     public Map<String, Object> variables() {
 *         return Map.of("id", userId);
 *     }
 *
 *     @Override
 *     public Class<UserDTO> responseType() {
 *         return UserDTO.class;
 *     }
 * }
 *
 * // Execute the operation
 * GraphiteClient client = ...;
 * GraphiteResponse<UserDTO> response = client.execute(new GetUserQuery("123"));
 * UserDTO user = response.data();
 * }</pre>
 *
 * @param <T> the type of data returned by this operation
 * @see GraphiteClient
 */
public interface GraphQLOperation<T> {

  /**
   * Returns the name of this GraphQL operation.
   *
   * <p>The operation name is used for:
   *
   * <ul>
   *   <li>Server-side logging and debugging
   *   <li>Apollo tracing and performance monitoring
   *   <li>Error message identification
   * </ul>
   *
   * <p>The name should follow GraphQL naming conventions (typically PascalCase) and be descriptive
   * of what the operation does.
   *
   * @return the operation name, never {@code null}
   */
  @NotNull
  String operationName();

  /**
   * Returns the GraphQL query or mutation string.
   *
   * <p>This is the complete GraphQL document that will be sent to the server, including the
   * operation type, name, variable definitions, and selection set.
   *
   * <p>Example return value:
   *
   * <pre>{@code
   * query GetUser($id: ID!) {
   *   user(id: $id) {
   *     id
   *     name
   *     email
   *   }
   * }
   * }</pre>
   *
   * @return the GraphQL query string, never {@code null}
   */
  @NotNull
  String toGraphQL();

  /**
   * Returns the variables to be sent with this operation.
   *
   * <p>Variables are used to parameterize GraphQL operations without string concatenation,
   * providing:
   *
   * <ul>
   *   <li>Type safety through GraphQL's type system
   *   <li>Query caching on the server side
   *   <li>Protection against injection attacks
   * </ul>
   *
   * <p>The map keys correspond to variable names defined in the operation, and the values must be
   * serializable to JSON.
   *
   * @return an immutable map of variable names to values, never {@code null}
   */
  @NotNull
  default Map<String, Object> variables() {
    return Collections.emptyMap();
  }

  /**
   * Returns the expected response type for this operation.
   *
   * <p>This class is used to deserialize the {@code data} field of the GraphQL response into the
   * appropriate type.
   *
   * @return the response type class, never {@code null}
   */
  @NotNull
  Class<T> responseType();
}
